
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: futureware-tech/simulator-action@v1
        with:
          model: "iPhone 12"
      - run: echo "whee"
