
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        model: ["iPhone 12"]
    steps:
      - uses: actions/checkout@v2
      - uses: futureware-tech/simulator-action@v1
        with:
          model: ${{ matrix.model }}
      - run: echo "whee"
